### ISSUE TITLE
Source data for the species table

### ISSUE THREAD

**Issue by patrickToca** [luanapp/using-gin#1]
Hi Luana. I cannot find the data for the species table. Do you plan to add it? maybe a CSV document.

**Comment by luanapp** [comment]
I'll do that soon, probably tomorrow
At least for unit testing or a initial dump for the database

**Comment by luanapp** [comment]
Added a small sample at https://github.com/luanapp/using-gin/blob/main/pkg/domain/species/mocks/species-mock.json

**Comment by patrickToca** [comment]
Thanks. Useful example.
